# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SentimentsTwitterHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('sample_size', models.CharField(max_length=100)),
                ('postive_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('negative_count', models.IntegerField()),
                ('neutral_tweets', models.TextField(max_length=100)),
                ('negative_tweets', models.TextField(max_length=100)),
                ('postive_tweets', models.TextField(max_length=100)),
                ('publication_date', models.DateField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Profile')),
            ],
        ),
    ]
