# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='Input #hashtag', max_length=150)),
            ],
        ),
    ]
