# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentstwitterhashtag',
            name='profile_id',
        ),
    ]
