# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0002_remove_sentimentstwitterhashtag_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentstwitterhashtag',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
