# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20181104_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentstwitterhashtag',
            name='negative_tweets',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentimentstwitterhashtag',
            name='neutral_tweets',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentimentstwitterhashtag',
            name='postive_tweets',
            field=models.TextField(max_length=100),
        ),
    ]
